[tool.autopep8]
max_line_length = 120
ignore = "E501,W6"  # or ["E501", "W6"] # https://github.com/hhatto/autopep8
in-place = true
recursive = true
aggressive = 3

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = ["C0330", "C0116", "C0114", "C0115", "C0103", "C0209", "W1203", "W1202"] # Missing function or method docstring (missing-function-docstring)