
name: cicd

on: [push]
jobs:
  commitStage:
    runs-on: ubuntu-latest
    env:      
      PROJECT: template
    steps:
      - uses: actions/checkout@main      
      - name: Setup Python Environment
        uses: actions/setup-python@v1
        with: 
          python-version: 3.9
      
      - name: 'build package'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt          
      
      - name: 'exceute testing'        
        run: |
          python -m unittest discover './tests/unit' 'test_*.py'
      

  uatStage:
    runs-on: ubuntu-latest
    needs: [commitStage]
    env:      
      PROJECT: template      
    steps:
      - uses: actions/checkout@main      

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'           

      
      - name: Setup Python Environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      
      - name: 'build package'
        shell: pwsh
        run: |
          ./build.ps1
      
      - name: 'deploy function'
        shell: bash
        run: |
          gcloud info
          gcloud config set project katarilab          
          gcloud functions deploy template-api-function --runtime python39 --trigger-http --entry-point=startup --set-env-vars CLOUD=GCP --region us-east4
          

  e2eStage:
    runs-on: ubuntu-latest
    needs: [uatStage]
    env:            
      PROJECT: template

    steps:
      - uses: actions/checkout@main      

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'      

      - name: Setup Python Environment
        uses: actions/setup-python@v1
        with: 
          python-version: 3.9
      
      - name: 'install python requirements'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt          
          pip install -r requirements-dev.txt          
      
      - name: 'execute testing'        
        run: |
          python -m unittest discover './tests/e2e' 'test_*.py'
  
  devops-stage:
    runs-on: ubuntu-latest
    needs: [commitStage, uatStage, e2eStage]
    if: ${{ always() }} 
    steps:
      - uses: actions/checkout@v2      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Finish :rocket:'